"""Ports for Git and sandbox execution."""

from pathlib import Path
from typing import Protocol

from vuzol.execution.domain import GitInspection, ProcessEnvelope
from vuzol.providers.ports import CodexProcessResult
from vuzol.workflows.ports import CancellationContext


class GitPort(Protocol):
    async def repository_identity(self, repository: Path) -> tuple[str, str | None]: ...
    async def resolve_commit(self, repository: Path, ref: str) -> str: ...
    async def require_clean_source(self, repository: Path) -> None: ...
    async def add_worktree(
        self, repository: Path, path: Path, branch: str, base_commit: str
    ) -> None: ...
    async def inspect(self, worktree: Path, base_commit: str | None = None) -> GitInspection: ...
    async def stage_paths(self, worktree: Path, paths: tuple[str, ...]) -> None: ...
    async def create_commit(self, worktree: Path, message: str) -> str: ...
    async def commit_parent(self, worktree: Path, commit: str) -> str: ...
    async def require_no_remotes(self, worktree: Path) -> None: ...
    async def require_clean_worktree(self, worktree: Path) -> None: ...
    async def remove_worktree(self, repository: Path, path: Path) -> None: ...


class SandboxRuntime(Protocol):
    async def preflight(self) -> None: ...
    async def run(
        self, envelope: ProcessEnvelope, cancellation: CancellationContext
    ) -> CodexProcessResult: ...
