"""create mvp persistence foundation

Revision ID: 332f4ecd3093
Revises:
Create Date: 2026-07-11 00:08:19.597291
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "332f4ecd3093"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "configuration_revisions",
        sa.Column("revision", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("normalized_content", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("artifact_reference", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_configuration_revisions")),
        sa.UniqueConstraint("revision", name=op.f("uq_configuration_revisions_revision")),
    )
    op.create_table(
        "events",
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("actor_type", sa.String(length=50), nullable=False),
        sa.Column("actor_id", sa.String(length=200), nullable=True),
        sa.Column("previous_state", sa.String(length=100), nullable=True),
        sa.Column("new_state", sa.String(length=100), nullable=True),
        sa.Column("correlation_id", sa.String(length=100), nullable=True),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
    )
    op.create_index(op.f("ix_events_correlation_id"), "events", ["correlation_id"], unique=False)
    op.create_index(op.f("ix_events_created_at"), "events", ["created_at"], unique=False)
    op.create_index(
        "ix_events_entity_time", "events", ["entity_type", "entity_id", "created_at"], unique=False
    )
    op.create_table(
        "external_inbox",
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("consumer", sa.String(length=100), nullable=False),
        sa.Column("external_event_id", sa.String(length=255), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("raw_payload_reference", sa.String(length=500), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "received",
                "processed",
                "rejected",
                "failed",
                name="inbox_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("outcome", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("linked_entity_type", sa.String(length=50), nullable=True),
        sa.Column("linked_entity_id", sa.UUID(), nullable=True),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_external_inbox")),
        sa.UniqueConstraint(
            "source", "consumer", "external_event_id", name="uq_inbox_external_identity"
        ),
    )
    op.create_table(
        "provider_profiles",
        sa.Column("stable_id", sa.String(length=100), nullable=False),
        sa.Column("configuration_revision", sa.String(length=64), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_profiles")),
        sa.UniqueConstraint("stable_id", name=op.f("uq_provider_profiles_stable_id")),
    )
    op.create_table(
        "tasks",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("source_chat_id", sa.BigInteger(), nullable=False),
        sa.Column("source_thread_id", sa.BigInteger(), nullable=True),
        sa.Column("project_id", sa.String(length=100), nullable=True),
        sa.Column("original_text", sa.Text(), nullable=False),
        sa.Column("transcript", sa.Text(), nullable=True),
        sa.Column("voice_reference", sa.String(length=500), nullable=True),
        sa.Column(
            "task_draft",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("draft_schema_version", sa.String(length=100), nullable=True),
        sa.Column("interpreter_profile", sa.String(length=100), nullable=True),
        sa.Column("prompt_version", sa.String(length=100), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "received",
                "interpreted",
                "context_prepared",
                "planned",
                "waiting_approval",
                "executing",
                "validating",
                "reviewing",
                "awaiting_user",
                "paused",
                "retrying",
                "quota_exhausted",
                "blocked",
                "failed",
                "cancelled",
                "rolled_back",
                "completed",
                name="task_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "risk",
            sa.Enum(
                "low",
                "medium",
                "high",
                "privileged",
                name="risk_level",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("task_type", sa.String(length=100), nullable=False),
        sa.Column("parent_task_id", sa.UUID(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_task_id"],
            ["tasks.id"],
            name=op.f("fk_tasks_parent_task_id_tasks"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
    )
    op.create_index(op.f("ix_tasks_project_id"), "tasks", ["project_id"], unique=False)
    op.create_table(
        "topic_mappings",
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("message_thread_id", sa.BigInteger(), nullable=False),
        sa.Column("topic_kind", sa.String(length=50), nullable=False),
        sa.Column("project_id", sa.String(length=100), nullable=True),
        sa.Column("accepts_new_tasks", sa.Boolean(), nullable=False),
        sa.Column("default_workflow", sa.String(length=100), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_topic_mappings")),
        sa.UniqueConstraint("chat_id", "message_thread_id", name="uq_topic_chat_thread"),
    )
    op.create_table(
        "interpretations",
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("original_input_hash", sa.String(length=64), nullable=False),
        sa.Column("transcript", sa.Text(), nullable=True),
        sa.Column("task_draft", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("profile_id", sa.String(length=100), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column("prompt_version", sa.String(length=100), nullable=False),
        sa.Column("schema_version", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
            name=op.f("fk_interpretations_task_id_tasks"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interpretations")),
    )
    op.create_index(
        op.f("ix_interpretations_task_id"), "interpretations", ["task_id"], unique=False
    )
    op.create_table(
        "profile_health_observations",
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("healthy", sa.Boolean(), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column(
            "detail",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "observed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("unhealthy_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rate_limit_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["provider_profiles.id"],
            name=op.f("fk_profile_health_observations_profile_id_provider_profiles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profile_health_observations")),
    )
    op.create_index(
        op.f("ix_profile_health_observations_profile_id"),
        "profile_health_observations",
        ["profile_id"],
        unique=False,
    )
    op.create_table(
        "runs",
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("workflow_type", sa.String(length=100), nullable=False),
        sa.Column("workflow_version", sa.String(length=100), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "created",
                "running",
                "paused",
                "blocked",
                "failed",
                "cancelled",
                "completed",
                name="run_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "selected_route",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("budget_mode", sa.String(length=30), nullable=False),
        sa.Column("configuration_revision", sa.String(length=64), nullable=False),
        sa.Column("policy_revision", sa.String(length=64), nullable=False),
        sa.Column("prompt_revision", sa.String(length=64), nullable=True),
        sa.Column("repository_revision", sa.String(length=64), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_category", sa.String(length=100), nullable=True),
        sa.Column("failure_summary", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_runs_task_id_tasks"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runs")),
    )
    op.create_index(op.f("ix_runs_task_id"), "runs", ["task_id"], unique=False)
    op.create_table(
        "transactional_outbox",
        sa.Column("destination", sa.String(length=100), nullable=False),
        sa.Column("operation_type", sa.String(length=100), nullable=False),
        sa.Column("linked_entity_type", sa.String(length=50), nullable=False),
        sa.Column("linked_entity_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=True),
        sa.Column("projection_revision", sa.Integer(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("artifact_reference", sa.String(length=500), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "leased",
                "delivered",
                "ambiguous",
                "dead_letter",
                name="delivery_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_error_category", sa.String(length=100), nullable=True),
        sa.Column("last_error_ambiguous", sa.Boolean(), nullable=False),
        sa.Column("lease_owner", sa.String(length=200), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_generation", sa.Integer(), nullable=False),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retention_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_transactional_outbox_event_id_events"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transactional_outbox")),
        sa.UniqueConstraint("destination", "idempotency_key", name="uq_outbox_idempotency"),
    )
    op.create_index(
        "ix_outbox_queue",
        "transactional_outbox",
        ["available_at", "created_at"],
        unique=False,
        postgresql_where=sa.text("status IN ('pending', 'ambiguous')"),
    )
    op.create_table(
        "clarification_decisions",
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("interpretation_id", sa.UUID(), nullable=True),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("deciding_user_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["interpretation_id"],
            ["interpretations.id"],
            name=op.f("fk_clarification_decisions_interpretation_id_interpretations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
            name=op.f("fk_clarification_decisions_task_id_tasks"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clarification_decisions")),
    )
    op.create_index(
        op.f("ix_clarification_decisions_task_id"),
        "clarification_decisions",
        ["task_id"],
        unique=False,
    )
    op.create_table(
        "routing_decisions",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("selected_profile_id", sa.String(length=100), nullable=True),
        sa.Column("alternatives", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("policy_revision", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
            name=op.f("fk_routing_decisions_run_id_runs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_routing_decisions")),
    )
    op.create_index(
        op.f("ix_routing_decisions_run_id"), "routing_decisions", ["run_id"], unique=False
    )
    op.create_table(
        "steps",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column(
            "dependency_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("step_type", sa.String(length=100), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "queued",
                "leased",
                "running",
                "waiting_approval",
                "blocked",
                "failed",
                "cancelled",
                "completed",
                name="step_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("executor_profile_id", sa.String(length=100), nullable=True),
        sa.Column(
            "required_capabilities",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "retry_class",
            sa.Enum(
                "never",
                "transient",
                "policy",
                name="retry_class",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "idempotency_class",
            sa.Enum(
                "read_only",
                "idempotent",
                "isolated_retryable",
                "non_idempotent",
                "unknown_effects_possible",
                name="idempotency_class",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("external_idempotency_key", sa.String(length=255), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("timeout_seconds", sa.Integer(), nullable=False),
        sa.Column("lease_owner", sa.String(length=200), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_generation", sa.Integer(), nullable=False),
        sa.Column("failure_category", sa.String(length=100), nullable=True),
        sa.Column("failure_summary", sa.Text(), nullable=True),
        sa.Column("unknown_effects", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_steps_run_id_runs"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_steps")),
        sa.UniqueConstraint("run_id", "ordinal", name="uq_steps_run_ordinal"),
    )
    op.create_index(
        op.f("ix_steps_executor_profile_id"), "steps", ["executor_profile_id"], unique=False
    )
    op.create_index(
        "ix_steps_lease_expiry",
        "steps",
        ["lease_expires_at"],
        unique=False,
        postgresql_where=sa.text("status IN ('leased', 'running')"),
    )
    op.create_index(
        "ix_steps_queue",
        "steps",
        ["priority", "available_at", "created_at"],
        unique=False,
        postgresql_where=sa.text("status = 'queued'"),
    )
    op.create_index(op.f("ix_steps_run_id"), "steps", ["run_id"], unique=False)
    op.create_table(
        "worktrees",
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.String(length=100), nullable=False),
        sa.Column("source_remote", sa.String(length=1000), nullable=True),
        sa.Column("base_commit", sa.String(length=64), nullable=False),
        sa.Column("branch", sa.String(length=255), nullable=False),
        sa.Column("path", sa.String(length=1000), nullable=False),
        sa.Column("owner", sa.String(length=200), nullable=False),
        sa.Column(
            "delivery_state",
            sa.Enum(
                "active",
                "worktree_retained",
                "patch_delivered",
                "applied",
                "merged",
                "pushed",
                "cleaned",
                name="worktree_delivery_state",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("result_commit", sa.String(length=64), nullable=True),
        sa.Column("cleaned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_worktrees_run_id_runs"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_worktrees_task_id_tasks"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_worktrees")),
        sa.UniqueConstraint("path", name=op.f("uq_worktrees_path")),
    )
    op.create_index(op.f("ix_worktrees_run_id"), "worktrees", ["run_id"], unique=False)
    op.create_index(op.f("ix_worktrees_task_id"), "worktrees", ["task_id"], unique=False)
    op.create_table(
        "approvals",
        sa.Column("step_id", sa.UUID(), nullable=False),
        sa.Column("action_envelope_hash", sa.String(length=64), nullable=False),
        sa.Column("requested_action", sa.Text(), nullable=False),
        sa.Column("normalized_target", sa.Text(), nullable=False),
        sa.Column("human_summary", sa.Text(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "approved",
                "rejected",
                "expired",
                "consumed",
                name="approval_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "requested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deciding_user_id", sa.BigInteger(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["step_id"], ["steps.id"], name=op.f("fk_approvals_step_id_steps"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approvals")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_approvals_token_hash")),
    )
    op.create_index(
        op.f("ix_approvals_action_envelope_hash"),
        "approvals",
        ["action_envelope_hash"],
        unique=False,
    )
    op.create_index(op.f("ix_approvals_step_id"), "approvals", ["step_id"], unique=False)
    op.create_table(
        "artifacts",
        sa.Column("task_id", sa.UUID(), nullable=True),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column("step_id", sa.UUID(), nullable=True),
        sa.Column("artifact_type", sa.String(length=100), nullable=False),
        sa.Column("content_uri", sa.String(length=1000), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("media_type", sa.String(length=200), nullable=False),
        sa.Column("sensitivity", sa.String(length=50), nullable=False),
        sa.Column("visibility", sa.String(length=50), nullable=False),
        sa.Column("retention_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_artifacts_run_id_runs"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["step_id"], ["steps.id"], name=op.f("fk_artifacts_step_id_steps"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_artifacts_task_id_tasks"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_artifacts")),
    )
    op.create_index(op.f("ix_artifacts_content_hash"), "artifacts", ["content_hash"], unique=False)
    op.create_index(
        op.f("ix_artifacts_retention_until"), "artifacts", ["retention_until"], unique=False
    )
    op.create_table(
        "usage_records",
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("profile_id", sa.String(length=100), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=True),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column("step_id", sa.UUID(), nullable=True),
        sa.Column("input_tokens", sa.BigInteger(), nullable=True),
        sa.Column("output_tokens", sa.BigInteger(), nullable=True),
        sa.Column("cached_tokens", sa.BigInteger(), nullable=True),
        sa.Column("cost_units", sa.Float(), nullable=True),
        sa.Column("quota_units", sa.Float(), nullable=True),
        sa.Column("duration_ms", sa.BigInteger(), nullable=False),
        sa.Column("provider_request_id", sa.String(length=255), nullable=True),
        sa.Column("outcome", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_usage_records_run_id_runs"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["step_id"],
            ["steps.id"],
            name=op.f("fk_usage_records_step_id_steps"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
            name=op.f("fk_usage_records_task_id_tasks"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usage_records")),
    )
    op.create_index(
        op.f("ix_usage_records_profile_id"), "usage_records", ["profile_id"], unique=False
    )
    op.create_index(
        op.f("ix_usage_records_provider_request_id"),
        "usage_records",
        ["provider_request_id"],
        unique=False,
    )
    op.create_table(
        "supervised_processes",
        sa.Column("step_id", sa.UUID(), nullable=False),
        sa.Column("command_envelope_hash", sa.String(length=64), nullable=False),
        sa.Column("working_directory", sa.String(length=1000), nullable=False),
        sa.Column("host_pid", sa.BigInteger(), nullable=True),
        sa.Column("container_id", sa.String(length=200), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "starting",
                "running",
                "terminating",
                "exited",
                "unknown",
                name="process_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("exit_code", sa.Integer(), nullable=True),
        sa.Column("signal_number", sa.Integer(), nullable=True),
        sa.Column("stdout_artifact_id", sa.UUID(), nullable=True),
        sa.Column("stderr_artifact_id", sa.UUID(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["stderr_artifact_id"],
            ["artifacts.id"],
            name=op.f("fk_supervised_processes_stderr_artifact_id_artifacts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["stdout_artifact_id"],
            ["artifacts.id"],
            name=op.f("fk_supervised_processes_stdout_artifact_id_artifacts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["step_id"],
            ["steps.id"],
            name=op.f("fk_supervised_processes_step_id_steps"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_supervised_processes")),
    )
    op.create_index(
        op.f("ix_supervised_processes_step_id"), "supervised_processes", ["step_id"], unique=False
    )
    op.create_table(
        "telegram_message_links",
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("message_thread_id", sa.BigInteger(), nullable=True),
        sa.Column("message_id", sa.BigInteger(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=True),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column("step_id", sa.UUID(), nullable=True),
        sa.Column("approval_id", sa.UUID(), nullable=True),
        sa.Column("message_role", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["approval_id"],
            ["approvals.id"],
            name=op.f("fk_telegram_message_links_approval_id_approvals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
            name=op.f("fk_telegram_message_links_run_id_runs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["step_id"],
            ["steps.id"],
            name=op.f("fk_telegram_message_links_step_id_steps"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
            name=op.f("fk_telegram_message_links_task_id_tasks"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_telegram_message_links")),
        sa.UniqueConstraint("chat_id", "message_id", name="uq_telegram_chat_message"),
    )
    op.create_table(
        "validation_results",
        sa.Column("step_id", sa.UUID(), nullable=False),
        sa.Column("validator_type", sa.String(length=100), nullable=False),
        sa.Column("command_hash", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("exit_code", sa.Integer(), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("artifact_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["artifact_id"],
            ["artifacts.id"],
            name=op.f("fk_validation_results_artifact_id_artifacts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["step_id"],
            ["steps.id"],
            name=op.f("fk_validation_results_step_id_steps"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_validation_results")),
    )
    op.create_index(
        op.f("ix_validation_results_step_id"), "validation_results", ["step_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_validation_results_step_id"), table_name="validation_results")
    op.drop_table("validation_results")
    op.drop_table("telegram_message_links")
    op.drop_index(op.f("ix_supervised_processes_step_id"), table_name="supervised_processes")
    op.drop_table("supervised_processes")
    op.drop_index(op.f("ix_usage_records_provider_request_id"), table_name="usage_records")
    op.drop_index(op.f("ix_usage_records_profile_id"), table_name="usage_records")
    op.drop_table("usage_records")
    op.drop_index(op.f("ix_artifacts_retention_until"), table_name="artifacts")
    op.drop_index(op.f("ix_artifacts_content_hash"), table_name="artifacts")
    op.drop_table("artifacts")
    op.drop_index(op.f("ix_approvals_step_id"), table_name="approvals")
    op.drop_index(op.f("ix_approvals_action_envelope_hash"), table_name="approvals")
    op.drop_table("approvals")
    op.drop_index(op.f("ix_worktrees_task_id"), table_name="worktrees")
    op.drop_index(op.f("ix_worktrees_run_id"), table_name="worktrees")
    op.drop_table("worktrees")
    op.drop_index(op.f("ix_steps_run_id"), table_name="steps")
    op.drop_index(
        "ix_steps_queue", table_name="steps", postgresql_where=sa.text("status = 'queued'")
    )
    op.drop_index(
        "ix_steps_lease_expiry",
        table_name="steps",
        postgresql_where=sa.text("status IN ('leased', 'running')"),
    )
    op.drop_index(op.f("ix_steps_executor_profile_id"), table_name="steps")
    op.drop_table("steps")
    op.drop_index(op.f("ix_routing_decisions_run_id"), table_name="routing_decisions")
    op.drop_table("routing_decisions")
    op.drop_index(op.f("ix_clarification_decisions_task_id"), table_name="clarification_decisions")
    op.drop_table("clarification_decisions")
    op.drop_index(
        "ix_outbox_queue",
        table_name="transactional_outbox",
        postgresql_where=sa.text("status IN ('pending', 'ambiguous')"),
    )
    op.drop_table("transactional_outbox")
    op.drop_index(op.f("ix_runs_task_id"), table_name="runs")
    op.drop_table("runs")
    op.drop_index(
        op.f("ix_profile_health_observations_profile_id"), table_name="profile_health_observations"
    )
    op.drop_table("profile_health_observations")
    op.drop_index(op.f("ix_interpretations_task_id"), table_name="interpretations")
    op.drop_table("interpretations")
    op.drop_table("topic_mappings")
    op.drop_index(op.f("ix_tasks_project_id"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_table("provider_profiles")
    op.drop_table("external_inbox")
    op.drop_index("ix_events_entity_time", table_name="events")
    op.drop_index(op.f("ix_events_created_at"), table_name="events")
    op.drop_index(op.f("ix_events_correlation_id"), table_name="events")
    op.drop_table("events")
    op.drop_table("configuration_revisions")
    # ### end Alembic commands ###
