"""add telegram intake and control actions

Revision ID: 7cdc769ba80a
Revises: 332f4ecd3093
Create Date: 2026-07-11 00:30:49.911952
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "7cdc769ba80a"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "332f4ecd3093"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "telegram_intake_messages",
        sa.Column("inbox_id", sa.UUID(), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("message_thread_id", sa.BigInteger(), nullable=False),
        sa.Column("message_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=True),
        sa.Column("original_text", sa.Text(), nullable=True),
        sa.Column(
            "attachments",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("affinity_kind", sa.String(length=50), nullable=True),
        sa.Column(
            "ambiguous_task_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "received",
                "awaiting_interpretation",
                "needs_clarification",
                "rejected",
                name="intake_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["inbox_id"],
            ["external_inbox.id"],
            name=op.f("fk_telegram_intake_messages_inbox_id_external_inbox"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
            name=op.f("fk_telegram_intake_messages_task_id_tasks"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_telegram_intake_messages")),
        sa.UniqueConstraint("chat_id", "message_id", name="uq_intake_chat_message"),
        sa.UniqueConstraint("inbox_id", name=op.f("uq_telegram_intake_messages_inbox_id")),
    )
    op.create_index(
        op.f("ix_telegram_intake_messages_task_id"),
        "telegram_intake_messages",
        ["task_id"],
        unique=False,
    )
    op.create_table(
        "telegram_control_actions",
        sa.Column("external_action_id", sa.String(length=255), nullable=False),
        sa.Column("action_kind", sa.String(length=50), nullable=False),
        sa.Column("requested_by_user_id", sa.BigInteger(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=True),
        sa.Column("step_id", sa.UUID(), nullable=True),
        sa.Column("approval_id", sa.UUID(), nullable=True),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "processed",
                "rejected",
                name="control_action_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["approval_id"],
            ["approvals.id"],
            name=op.f("fk_telegram_control_actions_approval_id_approvals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["step_id"],
            ["steps.id"],
            name=op.f("fk_telegram_control_actions_step_id_steps"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
            name=op.f("fk_telegram_control_actions_task_id_tasks"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_telegram_control_actions")),
        sa.UniqueConstraint(
            "external_action_id", name=op.f("uq_telegram_control_actions_external_action_id")
        ),
    )
    op.create_index(
        op.f("ix_telegram_control_actions_task_id"),
        "telegram_control_actions",
        ["task_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_telegram_control_actions_task_id"), table_name="telegram_control_actions"
    )
    op.drop_table("telegram_control_actions")
    op.drop_index(
        op.f("ix_telegram_intake_messages_task_id"), table_name="telegram_intake_messages"
    )
    op.drop_table("telegram_intake_messages")
    # ### end Alembic commands ###
