"""Backup foundation (B1), partial encrypted capture (B2), B3.0 package preflight."""

from vuzol.ops.backup.capture import BackupCaptureRunner, CaptureMode, CaptureReport
from vuzol.ops.backup.crypto import (
    CHUNK_PLAINTEXT_MAX,
    BackupCryptoError,
    decrypt_blob_stream,
    encrypt_blob_stream,
    generate_dek,
    unwrap_dek,
    wrap_dek,
)
from vuzol.ops.backup.manifest import (
    SCHEMA_VERSION,
    ArtifactReconciliation,
    BackupAppIdentity,
    BackupComponent,
    BackupConfigSnapshot,
    BackupManifest,
    BackupManifestError,
    BackupQuiesceInfo,
    BackupRetentionMeta,
    BackupRpoRto,
    BackupSchemaIdentity,
    ConfigFileHash,
    MissingBlobRecord,
    OrphanFileRecord,
    canonical_manifest_json,
    load_manifest,
    manifest_sha256,
    store_manifest,
    validate_manifest,
)
from vuzol.ops.backup.paths import (
    BackupPathError,
    ProductionRoots,
    assert_isolated_restore_dsn,
    assert_safe_restore_paths,
    database_name_is_isolated,
    normalize_dsn_identity,
    resolve_isolation_path,
)
from vuzol.ops.backup.restore import (
    BackupRestorePreflightError,
    PackagePreflightReport,
    preflight_published_package,
)
from vuzol.ops.backup.settings import BackupSettings
from vuzol.ops.backup.staging import assert_safe_staging_root

__all__ = [
    "CHUNK_PLAINTEXT_MAX",
    "SCHEMA_VERSION",
    "ArtifactReconciliation",
    "BackupAppIdentity",
    "BackupCaptureRunner",
    "BackupComponent",
    "BackupConfigSnapshot",
    "BackupCryptoError",
    "BackupManifest",
    "BackupManifestError",
    "BackupPathError",
    "BackupQuiesceInfo",
    "BackupRestorePreflightError",
    "BackupRetentionMeta",
    "BackupRpoRto",
    "BackupSchemaIdentity",
    "BackupSettings",
    "CaptureMode",
    "CaptureReport",
    "ConfigFileHash",
    "MissingBlobRecord",
    "OrphanFileRecord",
    "PackagePreflightReport",
    "ProductionRoots",
    "assert_isolated_restore_dsn",
    "assert_safe_restore_paths",
    "assert_safe_staging_root",
    "canonical_manifest_json",
    "database_name_is_isolated",
    "decrypt_blob_stream",
    "encrypt_blob_stream",
    "generate_dek",
    "load_manifest",
    "manifest_sha256",
    "normalize_dsn_identity",
    "preflight_published_package",
    "resolve_isolation_path",
    "store_manifest",
    "unwrap_dek",
    "validate_manifest",
    "wrap_dek",
]
