"""Typed configuration, registry, and secret-resolution boundary."""

from vuzol.config.loader import ConfigurationLoadError, build_bundle, load_document, merge_documents
from vuzol.config.models import (
    AgentEditMechanism,
    AgentRuntimeContract,
    BudgetMode,
    Capability,
    CommandDefinition,
    CostClass,
    DeliveryMode,
    EgressDestination,
    GitDeliveryPolicy,
    InnerSandboxMode,
    LaunchMode,
    NetworkPolicy,
    ProjectConfig,
    ProviderProfileConfig,
    ProviderRole,
    RegistryDocument,
    SandboxNetworkMode,
    SandboxProfileConfig,
    StructuredOutputSource,
    TopicConfig,
    TopicKind,
)
from vuzol.config.registries import (
    ConfigurationBundle,
    ProfileRegistry,
    ProjectRegistry,
    RegistryError,
    SandboxRegistry,
    TopicRegistry,
)
from vuzol.config.revision import RunConfigurationSnapshot, SnapshotCompatibility
from vuzol.config.runtime import RuntimeConfiguration, get_runtime_configuration
from vuzol.config.secrets import ScopedSecretResolver, SecretResolutionError
from vuzol.config.settings import (
    ConcurrencyLimits,
    DatabaseSettings,
    ExecutionSettings,
    HardLimits,
    InterpretationSettings,
    RetentionDefaults,
    Settings,
    TelegramSettings,
    WorkflowSettings,
    get_settings,
)

__all__ = [
    "AgentEditMechanism",
    "AgentRuntimeContract",
    "BudgetMode",
    "Capability",
    "CommandDefinition",
    "ConcurrencyLimits",
    "ConfigurationBundle",
    "ConfigurationLoadError",
    "CostClass",
    "DatabaseSettings",
    "DeliveryMode",
    "EgressDestination",
    "ExecutionSettings",
    "GitDeliveryPolicy",
    "HardLimits",
    "InnerSandboxMode",
    "InterpretationSettings",
    "LaunchMode",
    "NetworkPolicy",
    "ProfileRegistry",
    "ProjectConfig",
    "ProjectRegistry",
    "ProviderProfileConfig",
    "ProviderRole",
    "RegistryDocument",
    "RegistryError",
    "RetentionDefaults",
    "RunConfigurationSnapshot",
    "RuntimeConfiguration",
    "SandboxNetworkMode",
    "SandboxProfileConfig",
    "SandboxRegistry",
    "ScopedSecretResolver",
    "SecretResolutionError",
    "Settings",
    "SnapshotCompatibility",
    "StructuredOutputSource",
    "TelegramSettings",
    "TopicConfig",
    "TopicKind",
    "TopicRegistry",
    "WorkflowSettings",
    "build_bundle",
    "get_runtime_configuration",
    "get_settings",
    "load_document",
    "merge_documents",
]
